<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../classes/Oauth2Proxy.php';

/**
 * Test class for Oauth2Proxy.
 * Generated by PHPUnit on 2011-08-21 at 15:45:27.
 */
class Oauth2ProxyTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Oauth2Proxy
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Oauth2Proxy ();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @todo Implement testGetAccessToken().
	 */
	public function testGetAccessToken()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}
}
